### ISSUE TITLE
coverage doesn't write if directory to file doesn't already exist

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [direct-adv-interfaces/mocha-headless-chrome#23]
It'd be nice if there were [mkdirp](https://www.npmjs.com/package/mkdirp)-style logic if the `--coverage` directory path doesn't yet exist.

I'd be up for sending a PR to use `mkdirp.sync`, if you're up for it.

```
{ Error: ENOENT: no such file or directory, open 'C:\Code\Shenanigans\audioplayr\coverage\coverage.json'
    at Object.fs.openSync (fs.js:667:18)
    at Object.fs.writeFileSync (fs.js:1326:33)
    at runner.then.obj (C:\Code\Shenanigans\audioplayr\node_modules\mocha-headless-chrome\cli.js:38:28)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Code\\Shenanigans\\audioplayr\\coverage\\coverage.json' }
```

**Comment by dima117** [comment]
[Done](https://github.com/direct-adv-interfaces/mocha-headless-chrome/commit/7df8c7056f1e8b53dc07371a4a102dda8e6b3bff)
